// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProvaDS2Denner.Data;

namespace ProvaDS2Denner.Migrations
{
    [DbContext(typeof(ProvaDS2DennerContext))]
    [Migration("20191217021936_BdTrab")]
    partial class BdTrab
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProvaDS2Denner.Models.Confeccao", b =>
                {
                    b.Property<int>("ConfeccaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("PecaDeRoupaId")
                        .HasColumnType("int");

                    b.HasKey("ConfeccaoId");

                    b.HasIndex("PecaDeRoupaId");

                    b.ToTable("Confeccao");
                });

            modelBuilder.Entity("ProvaDS2Denner.Models.PecaDeRoupa", b =>
                {
                    b.Property<int>("PecaDeRoupaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("TipoDeRoupa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PecaDeRoupaId");

                    b.ToTable("PecaDeRoupa");
                });

            modelBuilder.Entity("ProvaDS2Denner.Models.Confeccao", b =>
                {
                    b.HasOne("ProvaDS2Denner.Models.PecaDeRoupa", "PecaDeRoupa")
                        .WithMany()
                        .HasForeignKey("PecaDeRoupaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
